default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: reportify_development

test:
  <<: *default
  database: reportify_test

production:
  <<: *default
  database: reportify_production
  username: reportify
  password: <%= ENV['DATABASE_PASSWORD'] %>
